theme: jekyll-whiteglass
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

#permalink: /:year/:month/:day/:title/

paginate_path: /page/:num/
paginate: 2

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

google_analytics: UA-97452588-1
lang: en-US
author: Dmitry Figol
title: Dmitry Figol
description: >
  Personal blog about networking and programming
excerpt_separator: <!--more-->

include: ['_pages']
twitter_username: dmfigol
linked_username:  dmitryfigol
github_username:  dmfigol
